name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Runs when pushing tags like v1.0.0

jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to checkout the repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Publish package to pub.dev
        run: dart pub publish --force
